// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Configuración de Firebase para cada plataforma.
///
/// Este archivo es generado automáticamente por FlutterFire CLI
/// y contiene las credenciales necesarias para conectar la app
/// con el proyecto de Firebase.
///
/// ⚠️ No modificar manualmente.
/// ⚠️ No borrar.
/// ⚠️ Si se cambia el proyecto de Firebase, regenerar con:
///     flutterfire configure
class DefaultFirebaseOptions {
  /// Devuelve la configuración correcta según la plataforma
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase no está configurado para esta plataforma.',
        );

      default:
        throw UnsupportedError('Plataforma no soportada.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv7IabhD_p3SibtnJoIgP3Zezpxw0Lw7M',
    appId: '1:172308856931:web:1e710552207bcf22fd7856',
    messagingSenderId: '172308856931',
    projectId: 'chatapp-26b3c',
    authDomain: 'chatapp-26b3c.firebaseapp.com',
    storageBucket: 'chatapp-26b3c.firebasestorage.app',
  );

  /// Configuración para Web

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnG1g2JHmvJTH3jxVudf6XKn3MpYqcMYQ',
    appId: '1:172308856931:android:f287b6170b7dde19fd7856',
    messagingSenderId: '172308856931',
    projectId: 'chatapp-26b3c',
    storageBucket: 'chatapp-26b3c.firebasestorage.app',
  );

  /// Configuración para Android
}